import '../../api/roles/methods.js';
import '/imports/api/roles/server/publications.js';
import '/imports/api/tags/server/publications.js';
import '/imports/api/tags/methods.js';
import '/imports/api/users/server/publications.js';
import '/imports/api/products/server/publications.js';
import '/imports/api/product_owners/methods.js';
import '/imports/api/partners/methods.js';
import '/imports/api/products/methods.js';
import '/imports/api/shops/methods.js';
import '/imports/api/balances/methods.js';
import '/imports/api/users/methods.js';
import '/imports/api/agencies/methods.js';
import '/imports/api/cards/methods.js';
import '/imports/api/user_cards/methods.js';
import '/imports/api/orders/methods.js';
import '/imports/api/user_roles/methods.js';
import '/imports/api/shop_cart/methods.js';
import '/imports/api/reg/methods.js';
import '/imports/api/role_order_status/methods.js';
import '/imports/api/order_status_accesses/methods.js';
import '/imports/api/balances/server/publications.js';
import '/imports/api/shops/server/publications.js';
import '/imports/api/products/server/publications.js';
import '/imports/api/fancyshop/methods.js';
import '/imports/api/apps/methods.js';
import '/imports/api/apps/http.js';
import '/imports/api/shop_orders/methods.js';
import '/imports/api/product_class/methods.js'
import '/imports/api/agency_relation/methods.js'
import '/imports/api/order_status/methods.js'